version: "3"

services:
  app:
    build: .
    container_name: nestjs
    ports:
      - "3000:3000"
    restart: always
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
  